### ISSUE TITLE
configuration for Hpc

### ISSUE THREAD

**Issue by ajerschow** [molmd/mispr#4]
Is the current configuration easily adapted to HPC implementation, including the slurm queuing system? What would one have to do in addition to package installation to integrate this well on HPC?

**Comment by rashatwi** [comment]
Hi @ajerschow. Yes, MISPR has support for various queuing systems including SLURM, via the FireWorks package in the backend. There are a set of configuration files that need to be created and configured after installing MISPR in order to automate the communication with the queuing system. Please check the documentation [here](https://www.molmd.org/mispr/html/installation/configuration.html#configuration-files) for more details on how to set these configuration files.
